<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>IDG TechNetwork | Publishers</title>
	
	<link rel="icon" type="image/x-ico" href="../favicon.ico" />
	<link rel="shortcut icon" type="image/x-icon" href="../favicon.ico" />
		
	<?php include("../inc/head.php"); ?>
	<?php
		$section = "publishers";
	?>
</head>
<body>
	<div id="container">
		<div id="header">
			<?php include("../inc/header.php"); ?>
			<?php include("../inc/nav.php"); ?>
		</div>
		<div id="content_wrapper">
			<div id="content">
				<div id="left_col">
					<?php include("../inc/publishers_nav.php"); ?>
				</div>
				<div id="column_container">
					<h2 id="publishers_header">Publishers</h2>
					<div id="center_col">
						<p>Offering benefits well beyond those of traditional ad networks,
						the IDG TechNetwork revolutionizes the market by enabling technology
						publishers to increase their revenues and grow their businesses.</p>
						<h3>The Power of the IDG TechNetwork Community of Sites</h3>
						<p>Independent publishers enjoy a suite of membership resources and
						services to increase traffic and revenue. Our network acts very much
						like an ecosystem. By cross-linking content from network and IDG
						sites, you are able to consistently grow site traffic from qualified
						audiences on member sites. What's more, IDG leverages its team of
						Web professionals to offer insights, best practices, and additional
						resources ideally suited to helping publishers grow their businesses.</p>
						<h3>Optimized Site Monetization</h3>
						<p>The primary objective of the IDG TechNetwork is to provide you,
						as a publisher, with incomparable revenue possibilities. IDG has
						over 120 advertising sales representatives in the U.S. and sales
						offices serving 85 countries around the world. IDG can bring your
						brand into more technology media buys than any other sales force.
						The result is higher CPM opportunities, deep advertising relationships,
						custom publishing revenues, better sell-through, and incremental
						revenue streams. Your content is placed next to premier advertisers
						in a contextually relevant environement. Furthermore, incremental
						traffic is generated and directed your way on an ongoing basis with
						SEO guidance and network traffic generated by the IDG TechNetwork
						community.</p>
						<p>The IDG TechNetwork provides the most comprehensive network to reach
						technology buyers in their preferred media environments. We have
						aggregated the best news, community, blogger and user group sites
						within the technology ecosystem. Whether you are trying to reach
						enterprise decision makers or gamers, the IDG TechNetwork brings
						you an increasingly broad range of marketing opportunities.</p>
						<h3>Partial List of Network Categories </h3>
						<table class="table">
							<tr>
								<td><h4>Network</h4></td>
								<td><h4>Category</h4></td>
							</tr>
							<tr>
								<td><p>B2B - IT</p></td>
								<td><ul>
									<li>Enterprise Applications</li>
									<li>Hardware</li>
									<li>Information Management</li>
									<li>Internet</li>
									<li>Mobile/Wireless/Telecommunications</li>
									<li>Networking</li>
									<li>Open Source (Linux/Unix)</li>
									<li>Security</li>
									<li>Software</li>
									<li>Storage</li>
									<li>Virtualization</li>
									<li>Web Services/SOA</li>
								</ul></td>
							</tr>
							<tr>
								<td><p>B2B &ndash; SMB</p></td>
								<td><ul>
									<li>Small and Medium Business</li>
								</ul></td>
							</tr>
							<tr>
								<td><p>B2C - Prosumer</p></td>
								<td><ul>
									<li>Components &ndash; Boards/Chips/Memory</li>
									<li>Consumer Electronics/ Peripherals/Services</li>
									<li>Games and Gaming</li>
									<li>Hardware</li>
									<li>Laptops/Desktops/Workstations</li>
									<li>Software</li>
								</ul></td>
							</tr>
						</table>
						<h3>Additional Membership Benefits </h3>
						<p>As a member publisher, you gain access to a robust package of valuable
						resources designed to support and enhance all your business objectives.</p>
						<h4>Membership services include:</h4>
						<ul>
							<li>Best practices guidelines</li>
							<li>24/7 online revenue reporting</li>
							<li>Rich networking and event opportunities</li>
							<li>VIP event access</li>
							<li>Network directory  listing and access</li>
							<li>Business development services</li>
							<li>Case studies</li>
						</ul>
						<h3>Find out more about joining the network or marketing opportunities
						available in the IDG TechNetwork:</h3>
						<p>Email us at <a href="mailto:publisherservices@idgsn.com">publisherservices@idgsn.com</a>.</p>
						<p><a href="jointhenetwork/"><img src="../imgs/join.gif" alt="Join the Network" width="156" height="28" border="0" /></a></p>
					</div>
					<div id="right_col">
						<?php include("../inc/featured_module.php"); ?>
					</div>
				</div>
			</div>
		</div>
		<?php include("../inc/footer.php"); ?>
	</div>
	<?php include("../inc/analytics.php"); ?>
</body>
</html>
